config/routes.rb
Travelpoker::Application.routes.draw do

  resources :create_slug_for_decks


  resources :create_slug_for_cards


  resource :cards_decks, only: [:create, :destroy]

  resources :decks do
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    member do
      post :copy
    end
  end

  resources :decks
    match '/feed' => 'decks#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  
  resources :cards do 
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    resources :comments do
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
      
  resources :users, only: [:show, :index] do
    resources :cards, only: [:index], controller: 'users/cards'
    resources :decks, only: [:index], controller: 'users/decks'
  end

  match "about" => 'welcome#about', via: :get
  match "how" => 'welcome#how', via: :get
  match "blog" => 'welcome#blog', via: :get
  match "faq" => 'welcome#faq', via: :get
  match "privacy" => 'welcome#privacy', via: :get
  match "terms" => 'welcome#terms', via: :get
  match "contact" => 'welcome#contact', via: :get
  match "sitemap" => 'welcome#sitemap', via: :get

  root :to => 'welcome#index'
end

app/views/mobile/layouts/_flash.html.erb
<div class="alert">
  <% if flash[:error] %>
    <%= flash[:error] %>
  <% end %>

  <% if flash[:notice] %>
    <%= flash[:notice] %>
  <% end %>

  <% if flash[:message] %>
    <%= flash[:message] %>
  <% end %>
</div>

app/views/mobile/layouts/_footer.html.erb
<div class="topFooter">
      <div class="centerDivMobile">
        <div class="footColMobile">
          <a href="/decks/new" class="btn btn-large btn-block creatDeck">Create a Deck</a>
        </div>
        <div class="footColMobile">
          <a href="/" class="footLogoMobile"></a>
        </div>  
      </div>
    </div>
    <footer>
      <div class="centerDiv">
        <ul class="footMenu">
          <li><a href="/privacy">Privacy Policy</a></li>
          <li><a href="/faq">FAQ</a></li>
          <li><a href="/contact">Contact Us</a></li>
          <li><a href="/terms">Ts & Cs</a></li>
        </ul>
        <p class="copyrights"> &copy; Copyrights 2013 all copyrights reserved - Travel Poker </p>
        <div class="footerSocialMobile">
            <a href="http://www.facebook.com/sharer.php?s=100&p[title]=TravelPoker&p[summary]=Inspired Travel&p[url]=www.travelpoker.co&p[images[0]=http://www.travelpoker.co/assets/homepage1.png" target="_blank" onclick="return !window.open(this.href, 'Facebook', 'width=640,height=300')" ><img src="/assets/facebookMobile.png"></a>
            <a href="http://twitter.com/share?url=http%3A%2F%2Fwww.travelpoker.co&text=Inspired%20Travel&media=https://lh6.googleusercontent.com/-zhmCkumDcYM/UoUnpfq7YvI/AAAAAAAABPk/VZbRePfm6rk/w190-h90-no/logo.png" target="_blank" onclick="return !window.open(this.href, 'Twitter', 'width=640,height=300')"><img src="/assets/twitterMobile.png"></a>
            <a href="https://plus.google.com/share?url=www.travelpoker.co&media=https://lh6.googleusercontent.com/-zhmCkumDcYM/UoUnpfq7YvI/AAAAAAAABPk/VZbRePfm6rk/w190-h90-no/logo.png" target="_blank" onclick="return !window.open(this.href, 'Google+', 'width=640,height=300')"><img src="/assets/gplusMobile.png"></a>
            <a href="http://pinterest.com/pin/create/button/?url=www.travelpoker.co&media=https://lh6.googleusercontent.com/-zhmCkumDcYM/UoUnpfq7YvI/AAAAAAAABPk/VZbRePfm6rk/w190-h90-no/logo.png&description=Inspired%20Travel" target="_blank" onclick="return !window.open(this.href, 'Pinterest', 'width=640,height=300')"><img src="/assets/pinterestMobile.png"></a>
          </div>
      </div>
      <%= yield :scripts %>
    </footer>

app/views/mobile/layouts/_panel.html.erb
<div class="allMobile">
  <div id="toppanel">
    <div id="panel">
    <div class="centerDiv">
      <% if user_signed_in? %>
        <div class="topCol1">
          <%= link_to current_user do%>
            <h4>My Likes</h4>
            <img src="/assets/mylikes.png">
          <% end %> 
        </div>
        <div class="topCol1">
          <%= link_to current_user do%>
            <h4>My Decks & Cards</h4>
            <img src="/assets/mydecks.png">
          <% end %> 
        </div>
        <div class="topCol1">
          <%= link_to current_user do%>
            <h4>I've Done</h4>
            <img src="/assets/mydone.png">
          <% end %> 
        </div>
        <div class="topCol1">
          <%= button_to('Logout', destroy_user_session_path, class: 'btn topButton', method: :delete) %>
          <a href="/decks/new" class="btn topButton">Create a Deck</a>
    
        </div>    
      <% else %>
        <div class="topColMobile">
          <%= render partial: '/devise/sessions/new' %>
         </div>
      <% end %>
    </div>  
    </div> <!-- /login -->  

  <!-- The tab on top --> 
    <div class="mobile">
      <div class="tab">
          
          <div id="toggle">
  
            <a id="open" class="open" href="#"><img src="/assets/plus.png"></a>
         
            <a id="close" style="display: none;" class="close" href="#"><img src="/assets/minus.png"></a> 

        </div> 
      </div> <!-- / top -->
    </div>
  </div> 
</div>

app/views/mobile/layouts/application.html.erb
<!DOCTYPE html>
 <html xmlns="http://www.w3.org/1999/xhtml"
       xmlns:fb="http://ogp.me/ns/fb#" >
  <head>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-45772305-1', 'travelpoker.co');
      ga('send', 'pageview');

    </script>

    <%= auto_discovery_link_tag :atom, "/feed" %>
    <%= auto_discovery_link_tag :rss, "/feed.rss" %>
    
    <link rel="shortcut icon" href="/assets/pokerlike.png"/>
     <title>Travel Poker</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" %>
    <%= javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places" %>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=0.37, maximum-scale=0.37, target-densitydpi=high-dpi, user-scalable=0" />
  </head>
<body> 
 <div class="allMobile"> 

  <%= render partial: 'layouts/panel' %>

  <div class="wrapper fade">
    <header class="mobileHeader">
      <div class="centerDivMobile">
        <a href="/"><div class="logoMobile"></div></a>

        <div class="hide">
        
        </div>
    
        <%= form_tag search_decks_path, :method => :get do %>
          <div class="searchHeadMobile">
            <%= text_field_tag :query, params[:query], placeholder: "Search Travel Cards" %> 
            <%= button_tag "Deal", class: "btnAll button btn buttonMobile" %>
         </div>  
       <% end %>  
      </div>
    </header>
    
      <% if flash[:error] || flash[:message] || flash[:notice] %>
      <div class="alert">
        <%= flash[:error] || flash[:message] || flash[:notice] %>
      </div>
      <% end %>

    <%= yield %>

    <%= render partial: 'layouts/footer' %>
  </div>  
</body>

</html>