config/routes.rb
Travelpoker::Application.routes.draw do

  resources :create_slug_for_decks


  resources :create_slug_for_cards


  resource :cards_decks, only: [:create, :destroy]

  resources :decks do
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    member do
      post :copy
    end
  end

  resources :decks
    match '/feed' => 'decks#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  
  resources :cards do 
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    resources :comments do
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
      
  resources :users, only: [:show, :index] do
    resources :cards, only: [:index], controller: 'users/cards'
    resources :decks, only: [:index], controller: 'users/decks'
  end

  match "about" => 'welcome#about', via: :get
  match "how" => 'welcome#how', via: :get
  match "blog" => 'welcome#blog', via: :get
  match "faq" => 'welcome#faq', via: :get
  match "privacy" => 'welcome#privacy', via: :get
  match "terms" => 'welcome#terms', via: :get
  match "contact" => 'welcome#contact', via: :get
  match "sitemap" => 'welcome#sitemap', via: :get

  root :to => 'welcome#index'
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  respond_to :html, :js, :xml, :json
  
  def index
    @cards = Card.order('created_at DESC').paginate(page: params[:page], per_page: 12)
    @decks = Deck.paginate(page: params[:page], per_page: 100)
  end
end

app/views/welcome/about.html.erb
 <%
    meta :title => "About - TravelPoker: Sharing Travel",
         :description => "TravelPoker is designed to inspire travel and discovery thoroughout the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.",
         :keywords => %w(Travel Inspired World sights experiences)
  %>

<div class="text">
    <h1>About TravelPoker</h1>
    <h6>TravelPoker is designed to inspire travel and discovery thoroughout the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.</h6>
    <p>Designed and built by Paddy Estridge as a project to help her learn programming, TravelPoker (and programming) proved to be pretty addictive, and grew into a project that records and arranges travel experiences all over the world</p>
</div>

app/views/welcome/blog.html.erb
 <%
    meta :title => "TravelPoker Blog, Sharing Travel",
         :description => "TravelPoker is designed to inspire travel and discovery thoroughout the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.",
         :keywords => %w(Travel Inspired World sights experiences)
  %>
<div class="text">
  <h1>We don't have a blog yet, but it's coming!</h1>
</div>

app/views/welcome/contact.html.erb
 <%
    meta :title => "Contact Us - TravelPoker: Sharing Travel",
         :description => "TravelPoker is designed to inspire travel and discovery thoroughout the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.",
         :keywords => %w(Travel Sharing Inspired World sights experiences)
  %>

<div class="text">
  <h1>Contact Us</h1>
  <p>Please contact us at <a href="paddy@travelpoker.co">paddy@travelpoker.co</a></p>
</div>

app/views/welcome/faq.html.erb
 <%
    meta :title => "FAQ - TravelPoker: Sharing Travel",
         :description => "TravelPoker is designed to inspire travel and discovery thoroughout the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.",
         :keywords => %w(Travel Inspired World sights experiences)
  %>

<div class="text">
  <h1>TravelPoker FAQ</h1>

  <h6>What is TravelPoker?</h6>
  <p>TravelPoker is a site designed to inspire people to travel and try new experiences - at home or abroad. Online travel is sometimes very utilitarian and dry, but that isn't waht travel is about. Travel is about experience, beauty, surprises, fun, and yes, sometimes mess! TravelPoker is intended to add to the fire of adventure, not make you worry if the sheets in a place will be clean.</p>
</div>

app/views/welcome/how.html.erb
 <%
    meta :title => "How TravelPoker Works - TravelPoker: Sharing Travel",
         :description => "Make a card for a place that you love, and create any combination of decks you like. You can plan your next adventure, make a deck of cards or friends visiting a place that you love, or gather experiences in your home town together - the choice is yours.",
         :keywords => %w(Travel Inspired World sights experiences)
  %>

<div class="text">

  <h1>How TravelPoker Works</h1>

  <h6>Make a card for a place that you love, and create any combination of "decks" you like. You can plan your next adventure, make a deck of cards or friends visiting a place that you love, or gather experiences in your home town together - the choice is yours.</h6>   
  <p></p>
</div>

app/views/welcome/index.html.erb
<%
    meta :title => "TravelPoker: Sharing Travel",
         :description => "TravelPoker is designed to inspire travel and discovery by helping users to find and share amazing experiences around the world. Travel experiences are put into cards, and collected together, in any arrangement that the user wants, into decks.",
         :keywords => %w(Travel Sharing World sights experiences)
%>

  <div class="centerDiv topSlider fade">
  <%= form_tag search_cards_path, :method => :get do %>
    <div class="searchIn">
      <%= text_field_tag :query, params[:query], placeholder: "Where or what are you looking for?" %> 
      <%= button_tag "Deal", class: "button" %>
   <!-- <input type="text" > -->
    </div>  
  <% end %>        
</div>

<div class="sliderContainer">
  <div id="slider-code">
    <div class="viewport">
      <ul class="overview">
          <li><a class="sliderTitle" href="/decks/5">A Perfect London Weekend</a><img src="/assets/homepage1.png" /></li>
          <li><a class="sliderTitle" href="/decks/7">Fire and Brimstone in The UK's South East</a><img src="/assets/homepage2.png" /></li>
          <li><a class="sliderTitle" href="/decks/6">Beautiful Budapest in Two Days</a><img src="/assets/homepage3.png" />/li>
          <li><a class="sliderTitle" href="/decks/8">The Alps  Top 10</a><img src="/assets/homepage4.png" /></li>
      </ul>
    </div>
  </div>
</div>

<div class="topDeck">
    <h3>Top Decks</h3>
     <div class="apple_pagination">
      <%= will_paginate @decks %>
    </div>
    <%= render @decks %>
</div>

<div class="topDeck">
  <h3>Top Cards</h3>
  <div class="apple_pagination">
    <%= will_paginate @cards %>
  </div>

  <%= render @cards %>
    
  <%= render partial: 'cards/show', collection: @cards, as: :card %>
           
</div>
    