config/routes.rb
Travelpoker::Application.routes.draw do

  resources :create_slug_for_decks


  resources :create_slug_for_cards


  resource :cards_decks, only: [:create, :destroy]

  resources :decks do
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    member do
      post :copy
    end
  end

  resources :decks
    match '/feed' => 'decks#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  
  resources :cards do 
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    resources :comments do
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
      
  resources :users, only: [:show, :index] do
    resources :cards, only: [:index], controller: 'users/cards'
    resources :decks, only: [:index], controller: 'users/decks'
  end

  match "about" => 'welcome#about', via: :get
  match "how" => 'welcome#how', via: :get
  match "blog" => 'welcome#blog', via: :get
  match "faq" => 'welcome#faq', via: :get
  match "privacy" => 'welcome#privacy', via: :get
  match "terms" => 'welcome#terms', via: :get
  match "contact" => 'welcome#contact', via: :get
  match "sitemap" => 'welcome#sitemap', via: :get

  root :to => 'welcome#index'
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :user
  belongs_to :season
  belongs_to :category
  has_many :comments, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :dones, as: :doable, dependent: :destroy
  has_and_belongs_to_many :decks, uniq: true
  attr_accessible :description, :image, :remote_image_url, :location, :title, :url, :season, :category, :slugged, :category_id, :season_id

  mount_uploader :image, ImageUploader

  extend FriendlyId
  friendly_id :title, use: :slugged

  acts_as_gmappable process_geocoding: true, check_process: false

  def gmaps4rails_address
    #describe how to retrieve the address from your model, if you use directly a db column, you can dry your code, see wiki
    "#{self.location}" 
  end

  searchable do
    text :title, :description, :location
  end
  
  validates :title, length: { 
    minimum: 5,
    maximum: 50 }
  validates :description, length: { minimum: 20 }
  validates :user, presence: true 

end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  respond_to :json, :html, :js, :xml

  def index
    @cards = Card.order('created_at DESC').paginate(page: params[:page], per_page: 12)
  end

  def show
    @card = Card.find(params[:id])

    if @card
       @comments = @card.comments.includes(:user)
       @json = @card.to_gmaps4rails
       respond_with(@card, @json)
    else
      redirect_to :root
    end
  end

  def search
    
    @cards = Card.search do
      keywords params[:query]
    end.results

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @cards }
      format.json { render :json => @cards}
    end
  end

  def new
    @card = Card.new
    authorize! :create, Card, message: "Please Register with TravelPoker to create your own cards."
  end

  def create
    @card = Card.new(params[:card])
    @card.user = current_user
    authorize! :create, Card, message: "Please Register with TravelPoker to create your own cards."
    
    if @card.save
      respond_with(@card)
    else
      flash[:error] = "There was an error saving the card. Please see errors below."
      render :new
    end
  end

  def update
    @card = Card.find(params[:id])
    
      if @card.update_attributes(params[:card])
        respond_with(@card)
      else
        flash[:error] = "There was an error saving the card. Please make sure all of the information is filled in."
        render :edit
      end
  end
  
  def edit
    @card = Card.find(params[:id])
    authorize! :edit, Card, message: "You must own a card to edit it."
    respond_with(@card)
  end

  def destroy
    @card = Card.find(params[:id])
    authorize! :destroy, Card, message: "You must own a card to delete it."
    title = @card.title
     
    if @card.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      respond_with :root
    else
      flash[:error] = "There was an error deleting the card."
      render :show
    end
  end
end

    #autocomplete = client.autocomplete(:input => :query)
    #autocomplete.predictions.first.description

app/controllers/users/cards_controller.rb
class Users::CardsController < ApplicationController  
  def index
    @cards = User.find(params[:user_id]).cards
    @cards = @cards.paginate(page: params[:page], per_page: 12)
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_card.html.erb
<div class="card trip <%= dom_id(card) %>" >
<a href="#">
  <div class="edit">
    <%= render partial: 'decks/carddeck', locals: { card: card } %>
  </div>
  <%= image_tag(card.image.front) %>
  <div class="tripInfo">
    <h4><%= link_to card.title, card %></h4>
    <p><%= markdown (card.location)%></p>
  </div> 
   <div class="tripMeta">
      <%= render partial: 'dones/done', locals: { doable: card } %>
      <%= render partial: 'likes/like', locals: { likeable: card } %>
   </div>
   
</a>
</div>








 

app/views/cards/_keep.html.erb
<% unless action_name == 'edit' %>
  <div class="dk_container dk_shown">
    <div class="keep">
      <span class="dk_label">Add Card To A Deck</span>
    </div>
    <div class="keepOptions">
      <ul class="keepOptions_inner">
        <% if current_user %>
          <% current_user.decks.each do |deck| %>
            <li class="">
              <%= link_to "To: #{deck.title}", cards_decks_path(card_id: card.id, deck_id: deck.id), method: :post, method: :post, remote: true, data: { 'dk-dropdown-value' => 0 } %>
            </li>
          <% end %>
          <li>
            <a href="/decks/new">Create a Deck</a>
          </li>
        <% else %>
          <li><a href="/decks/new/" data-dk-dropdown-value="1">Log In To Save Card?</a></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/cards/_show.html.erb
<div class="card back hide <%= dom_id(card) %>">

 <div class="twistCenter">
  <div class="twistCardBack"></div>
 
      <a class="prev" href="#"><img src="/assets/leftarrow.png"></a>
      <div class="twistCard"> 
        
        <div class="twistTitle">
          <h7><%= card.title%>: <span class= 'location'><%= card.location%></span></h7>
        </div>
          <h8><%= link_to card.user.name %> contributed <%= time_ago_in_words(card.created_at) %> ago</h8>
        
          <div class="image">
             <div class="map"></div> 
            <%= image_tag card.image%>
          </div>

          <div class="tripInfoBackTwist">
            <h4><%= link_to card.title, card %>: <%=link_to card.location, card%></h4>
          </div>

          <div class="backInfo">
            
          <div class="tags">
            <div class="category"><h4>Category</h4><%=image_tag card.category.image, title: card.category.title %></div>
            <div class="season"><h4>Season</h4><%=image_tag card.season.image %></div>
          </div> 

          <div class="cardComs">
            
            <div class=""><%= render partial: 'dones/done', locals: { doable: card } %></div>
            <div class=""><%= render partial: 'likes/like', locals: { likeable: card } %></div>
            <%= render partial: 'cards/social', locals: { card: card } %>
            <%= render partial: 'cards/keep', locals: { card: card } %>
           
            <% if can? :manage, card %>
              <div class="memberOnly">
                <span><%= link_to "Edit", edit_card_path(card), class: "dk_label editDelete" %></span>
                <span> <%= link_to "Delete", card, method: :delete, class: "dk_label editDelete", confirm: 'Are you sure you want to delete this card?' %></span>
              </div>
            <% end %>
          </div>

              <p><%= card.description%></p>
              <p><%= link_to card.url, card.url %></p>
              <h4>Decks this Card is Part of</h4>
              <% card.decks.each do |deck| %>
                <%= link_to deck.title, deck %><br>
              <% end %>
          </div> 

            <div class="comments">  
               <h4 class='js-comments-count'><%= card.comments.count %> Additional Thoughts</h4>
              <div class="js-comments"> 
                <%= render partial: "comments/comment", collection: card.comments, locals: { card: @cards} %>
              </div>
                <%= render partial: "comments/form", locals:{ card: card, comment: Comment.new } %>
            </div>

          <div class="advert">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- tp backs -->
            <ins class="adsbygoogle"
                 style="display:inline-block;width:728px;height:90px"
                 data-ad-client="ca-pub-1244420710031131"
                 data-ad-slot="9375366351"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
          </div>  
       
      </div>
      <a class="next" href="#"><img src="/assets/rightarrow.png"></a>
  </div>

</div>
 

app/views/cards/show.html.erb
<span itemscope itemtype="http://data-vocabulary.org/Review">
  <div class="topDeck">
    <%
      meta :title => @card.title,
           :description  => @card.description,
           :keywords => %w(Travel Sharing Inspired @card.location @card.title)
    %>
    
    <h3><span itemprop="itemreviewed"><%= @card.title%></span>: <span itemprop="address"><%= @card.location %></span></h3>
  </div>

  <div class="tripBack">
      <h8>
        <% if (@card.user.name != nil) %>
          <span itemprop="reviewer"><%= link_to @card.user.name %></span> contributed <time itemprop="dtreviewed" datetime="(@card.created_at).to_date"><%= time_ago_in_words(@card.created_at) %></span> ago
        <% else %>
          <span itemprop="reviewer"><%= link_to @card.user.id %></span> contributed <time itemprop="dtreviewed" datetime="(@card.created_at).to_date"><%= time_ago_in_words(@card.created_at) %></span> ago
        <% end %>
      </h8>
     <%= gmaps4rails(@json) %>
     <%= image_tag @card.image, :alt => @card.title %>
    <div class="tripInfoBack">
      <h3><%= @card.title%>: <%= @card.location%></h3>
    </div>

    <div class="ad">
      <script type="text/javascript"><!--
        google_ad_client = "ca-pub-1244420710031131";
        /* tp */
        google_ad_slot = "5656091157";
        google_ad_width = 300;
        google_ad_height = 600;
        //-->
      </script>
      <script type="text/javascript" src="//pagead2.googlesyndication.com/pagead/show_ads.js"></script>
    </div>

   <div class="cardComs">
      
      <div class=""><%= render partial: 'dones/done', locals: { doable: @card } %></div>
      <div class=""><%= render partial: 'likes/like', locals: { likeable: @card } %></div>
      <%= render partial: 'cards/social', locals: { card: @card } %>
      <%= render partial: 'cards/keep', locals: { card: @card } %>
     
      <% if can? :manage, @card %>
      <div class="memberOnly">
        <span><%= link_to "Edit", edit_card_path(@card), class: "dk_label editDelete" %></span>
        <span> <%= link_to "Delete", @card, method: :delete, class: "dk_label editDelete", confirm: 'Are you sure you want to delete this card?' %></span>
      </div>
      <% end %>
    </div>

    <div class="backInfo">
       
       <div class="tags">
         <div class="category"><h3>Category</h3><%=image_tag @card.category.image, title: @card.category.title %></div>
         <div class="season"><h3>Season</h3><%=image_tag @card.season.image %></div>
       </div>
    
      <p><span itemprop="description"><%= @card.description%></span></p>
      <p><%= link_to @card.url%></p>
      <h3>Decks this Card is Part of</h3>
      <% @card.decks.each do |deck| %>
        <%= link_to deck.title, deck %><br>
      <% end %>

      <div class="comments">  
        <h3 class='js-comments-count'><%= @comments.count %> Additional Thoughts</h3>
          <div class="js-comments"> 
            <%= render partial: "comments/comment", collection: @comments, locals: { card: @cards} %>
          </div>
            <%= render partial: "comments/form", locals:{ card: @card, comment: Comment.new } %>
      </div>
    </div>
  </div>
</span>