config/routes.rb
Travelpoker::Application.routes.draw do

  resources :create_slug_for_decks


  resources :create_slug_for_cards


  resource :cards_decks, only: [:create, :destroy]

  resources :decks do
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    member do
      post :copy
    end
  end

  resources :decks
    match '/feed' => 'decks#feed',
      :as => :feed,
      :defaults => { :format => 'atom' }
  
  resources :cards do 
    collection do
      get :search
    end
    resources :likes, only: [:create, :destroy]
    resources :dones, only: [:create, :destroy]
    resources :comments do
      match '/up-vote', to: 'votes#up_vote', as: :up_vote
      match '/down-vote', to: 'votes#down_vote', as: :down_vote
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
      
  resources :users, only: [:show, :index] do
    resources :cards, only: [:index], controller: 'users/cards'
    resources :decks, only: [:index], controller: 'users/decks'
  end

  match "about" => 'welcome#about', via: :get
  match "how" => 'welcome#how', via: :get
  match "blog" => 'welcome#blog', via: :get
  match "faq" => 'welcome#faq', via: :get
  match "privacy" => 'welcome#privacy', via: :get
  match "terms" => 'welcome#terms', via: :get
  match "contact" => 'welcome#contact', via: :get
  match "sitemap" => 'welcome#sitemap', via: :get

  root :to => 'welcome#index'
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  belongs_to :user
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :dones, as: :doable, dependent: :destroy
  has_and_belongs_to_many :cards, uniq: true
  attr_accessible :image, :remote_image_url,:description, :title, :slugged

  default_scope order('updated_at DESC')

  mount_uploader :image, ImageUploader

  validates :title, length: { minimum: 5 }, presence: true
  validates :user, presence: true 

  extend FriendlyId
  friendly_id :title, use: :slugged

  searchable do
    text :title, :description, :cards
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  respond_to :html, :js, :xml, :json
  
  def index
    @decks = Deck.paginate(page: params[:page], per_page: 24)
  end

  def show
     @deck = Deck.find(params[:id])
     @cards = @deck.cards.includes(:user).order('created_at DESC')
     @json = @deck.cards.to_gmaps4rails
  end

  def search
    
    @decks = Deck.search do
      keywords params[:query]
    end.results

    respond_to do |format|
      format.html { render :action => "index" }
      format.xml  { render :xml => @decks }
    end
  end


  def new
    @deck = Deck.new
    authorize! :create, Deck, message: "Please Register with TravelPoker to create your own decks."
    @cards = Card.all
  end

  def create
    @deck = current_user.decks.new(params[:deck])
    authorize! :create, Deck, message: "Please Register with TravelPoker to create your own cards."
    
    if @deck.save
      flash[:notice] = "Deck was saved."
      redirect_to edit_deck_path(@deck)
    else
      flash[:error] = "There was an error saving the deck. Please try again."
      render :new 
    end
  end

  def update
    @deck = Deck.find(params[:id])
    
    if @deck.update_attributes(params[:deck])
      flash[:notice] = "Deck was updated."
      redirect_to @deck, notice: "Deck was saved successfully."
    else
      flash[:error] = "There was an error saving the deck. Please try again."
      render :edit
    end
  end

  def edit
    @deck = Deck.find(params[:id])
    authorize! :edit, Deck, message: "You must own a deck to edit it."
    @cards = Card.paginate(page: params[:page], per_page: 12) do |card|
      not @deck.cards.include?(card)
    end
  end

  def destroy
    @deck = Deck.find(params[:id])
    authorize! :destroy, Deck, message: "You must own a deck to delete it."
    title = @deck.title
     
    if @deck.destroy
      flash[:notice] = "\"#{title}\" was deleted successfully."
      redirect_to decks_path
    else
      flash[:error] = "There was an error deleting the deck."
      render :show
    end
  end

 def copy
    @deck = Deck.find(params[:id])
    @deck_copy = @deck.dup
    @deck_copy.user = current_user
    @deck_copy.remote_image_url = @deck.image.url
    @deck_copy.cards << @deck.cards
    
    if @deck_copy.save
      flash[:notice] = "Deck was saved."
      redirect_to @deck_copy
    else
      flash[:error] = "There was an error saving the deck. Please try again."
      render :new 
    end
  end

  def feed
    # this will be the name of the feed displayed on the feed reader
    @title = "Travel Poker Feed"

    # the news items
    @decks = Deck.order("updated_at desc")

    # this will be our Feed's update timestamp
    @updated = @decks.first.updated_at unless @decks.empty?

    respond_to do |format|
      format.atom { render :layout => false }

      # we want the RSS feed to redirect permanently to the ATOM feed
      format.rss { redirect_to feed_path(:format => :atom), :status => :moved_permanently }
    end
  end
end

app/controllers/users/decks_controller.rb
class Users::DecksController < ApplicationController
  def index
    @decks = User.find(params[:user_id]).decks
    @decks = @decks.paginate(page: params[:page], per_page: 12)
  end

  def show
    @decks = User.find(params[:user_id]).decks
    @decks = @decks.paginate(page: params[:page], per_page: 12)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_deck.html.erb
<%= link_to deck do %>
  <div class="deck">
    <div class="tripMeta">
      <%= render partial: 'likes/like', locals: { likeable: deck } %>
    </div>
    <%= link_to deck do %>
      <%= image_tag (deck.image.front) %>
    <% end %>
    <div class="tripInfo">
      <h4><%= link_to deck.title, deck %></h4>
    </div>
  </div>
<% end %>

app/views/decks/_keep.html.erb
<% unless action_name == 'edit' %>
  <div class="dk_container dk_shown">
    <a class="keep">
      <span class="dk_label">Copy Deck</span>
    </a>
    <div class="keepOptions">
      <ul class="keepOptions_inner">
        <% if current_user %>
          <li class="">
            <%= link_to "Keep Deck", copy_deck_path(deck), method: :post %>
          </li>
        <% else %>
          <li><a href="/decks/new/" data-dk-dropdown-value="1">Log In To Copy Deck?</a></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/decks/edit.html.erb
<div class="topDeck">
  <h3>Add Cards To <%= @deck.title %></h3>
</div>
<div class="editDeck">
  <img class="cover" src="/assets/hide2.png">
  <div class="openEdit"></div><h4>Edit Title, Description and Image</h4>
  <img class="cover" src="/assets/hide2.png">
</div>

  <%= render partial: 'form', locals: { deck: @deck } %>

<div class="topDeck">
  <h3>Current Cards in Deck</h3>
    <div class="addedCard">
      <%= render @deck.cards %>
    </div>
</div>
<div class="topDeck">
  <h3>Add Cards To Deck</h3>
    <div class="removedCard">

      <div class="apple_pagination">
        <%= will_paginate @cards %>
      </div>
      
      <%= render @cards %>

    </div>
</div>

app/views/decks/index.html.haml
<div class="topDeck">
  <h3>Top Decks</h3>
    <%= render partial: 'deck', collection: @decks %>
    <%= will_paginate @decks %>
</div>

app/views/decks/show.html.erb
<span itemscope itemtype="http://data-vocabulary.org/Review">
  <div class="topDeck" itemscope itemtype="http://data-vocabulary.org/Review">
    <%
      meta :title => @deck.title,
           :description  => @deck.description,
           :keywords => %w(Travel Sharing Inspired @card.location @card.title)
    %>
    <h3><span itemprop="itemreviewed"><%= @deck.title %></h3></span>
  </div>

  <div class="deckBack">
      <h8>
        <% if (@deck.user.name != nil) %>
          <span itemprop="reviewer"><%= link_to @deck.user.name %></span> contributed <time itemprop="dtreviewed" datetime="(@deck.created_at).to_date"> <%= time_ago_in_words(@deck.created_at) %> ago</time>
        <% else %>
          <span itemprop="reviewer"><% link_to @deck.user.id %></span> contributed on <time itemprop="dtreviewed" datetime="(@deck.created_at).to_date"><%= time_ago_in_words(@deck.created_at) %> ago </time>
        <% end %>
      </h8>
      <%= gmaps4rails(@json) %>
      <%= image_tag @deck.image, :alt => @deck.title%>
      <div class="tripInfoBack">
        <h3><span itemprop="summary"><%= @deck.title%></h3></span>
      </div>

  </div>

  <div class="deckDescription">
    <div class="deckComs">
      <div class=""><%= render partial: 'likes/like', locals: { likeable: @deck } %></div>
      <%= render partial: 'decks/keep', locals: { deck: @deck } %>
      <%= render partial: 'decks/social', locals: { deck: @deck } %>
      <% if can? :manage, @deck %>
        <div class="memberOnly">
          <span><%= link_to "Edit", edit_deck_path(@deck), class: "editDelete" %></span>
          <span> <%= link_to "Delete", @deck, method: :delete, class: "editDelete", confirm: 'Are you sure you want to delete this deck?' %></span>
        </div>
      <% end %>
    </div>

    <p><span itemprop="description"><%= @deck.description%></p></span>
  </div>

    <div class="deckCards">
        <%= render @cards %>
          
        <%= render partial: 'cards/show', collection: @cards, as: :card %>
    </div>
  </div>
</span>